### ISSUE TITLE
Increase the opacity of navbar

### ISSUE THREAD

**Issue by Aju100** [lgcolella/gatsby-starter-developer-blog-v2#1]
Hi there, after experimenting with this blog project, for the enhancement of the blog, opacity should be increased while we navigate in the mobile view.
![nav](https://user-images.githubusercontent.com/29862610/97838011-556a3d80-1d05-11eb-9eb5-457c015fcc92.png)

**Comment by luigi-colella** [comment]
Hi @Aju100 and thank you for your feedback. I fixed the issue. 👍

**Comment by Aju100** [comment]
@lgcolella cool
