### ISSUE TITLE
[FEATURE] Integrate disqus for commenting

### ISSUE THREAD

**Issue by Aju100** [lgcolella/gatsby-starter-developer-blog-v2#2]
@lgcolella  Having commenting features in a blog post will give much more interaction with the audience. It will be a good idea to integrate Disqus in this blog project. Thank you

**Comment by luigi-colella** [comment]
@Aju100 Thank you for your interest in this starter! I'll work on that in my spare time. In the meanwhile you can see it how I implemented this feature in another project [here](https://github.com/lgcolella/gatsby-starter-developer-blog/tree/master/src/templates/post/comments) and open a PR if you want.

**Comment by luigi-colella** [comment]
@Aju100 Disqus added https://github.com/lgcolella/gatsby-starter-developer-blog-v2/commit/1ec5b74137c0b0794c20a52650db8597a314e6d3.

**Comment by Aju100** [comment]
@lgcolella  thank you but I had implemented through your previous codebase which was implemented in Js. As I am learning so wouldn't make to open PR using TSX one .
